export const SOCKET_EVENTS = {
  MESSAGE_PRIVATE: "MESSAGE:PRIVATE",
  MESSAGE_PRIVATE_UPDATED: "MESSAGE:PRIVATE:UPDATED",
  MESSAGE_PRIVATE_DELETED: "MESSAGE:PRIVATE:DELETED",

  MESSAGE_ROOM: "MESSAGE:ROOM",
  MESSAGE_ROOM_UPDATED: "MESSAGE:ROOM:UPDATED",
  MESSAGE_ROOM_DELETED: "MESSAGE:ROOM:DELETED",

  NOTIFICATION_NEW: "NOTIFICATION:NEW",
  NOTIFICATION_READ: "NOTIFICATION:READ",

  FRIEND_REQUEST: "FRIEND:REQUEST",
  FRIEND_ACCEPT: "FRIEND:ACCEPT",
  FRIEND_REMOVE: "FRIEND:REMOVE",

  CALL_OFFER: "CALL:OFFER",
  CALL_ANSWER: "CALL:ANSWER",
  CALL_REJECT: "CALL:REJECT",
  CALL_ICE_CANDIDATE: "CALL:ICE_CANDIDATE",
  CALL_END: "CALL:END",
  CALL_BUSY: "CALL_BUSY",
  CALL_CANCEL: "CALL_CANCEL",

  MISSION_CREATED: "MISSION:CREATED",
  MISSION_ASSIGNED: "MISSION:ASSIGNED",
  MISSION_UPDATED: "MISSION:UPDATED",
  MISSION_DELETED: "MISSION:DELETED",

  MACHINE_CREATED: "MACHINE:CREATED",
  MACHINE_UPDATED: "MACHINE:UPDATED",
  MACHINE_DELETED: "MACHINE:DELETED",

  ALERT_CREATED: "ALERT:CREATED",
  ALERT_UPDATED: "ALERT:UPDATED",
  ALERT_DELETED: "ALERT:DELETED",

  KPI_UPDATE: "KPI:UPDATE",
  LATEST_ACTIVITIES: "LATEST_ACTIVITIES",
  MATERIAL_UPDATE: "MATERIAL:UPDATE",
};
