export const SOCKET_EVENTS = {
  MESSAGE_PRIVATE: "MESSAGE:PRIVATE",
  MESSAGE_PRIVATE_UPDATED: "MESSAGE:PRIVATE:UPDATED",
  MESSAGE_PRIVATE_DELETED: "MESSAGE:PRIVATE:DELETED",

  MESSAGE_ROOM: "MESSAGE:ROOM",
  MESSAGE_ROOM_UPDATED: "MESSAGE:ROOM:UPDATED",
  MESSAGE_ROOM_DELETED: "MESSAGE:ROOM:DELETED",

  NOTIFICATION_NEW: "NOTIFICATION:NEW",
  NOTIFICATION_READ: "NOTIFICATION:READ",

  FRIEND_REQUEST: "FRIEND:REQUEST",
  FRIEND_ACCEPT: "FRIEND:ACCEPT",
  FRIEND_REMOVE: "FRIEND:REMOVE",

  MISSION_ASSIGNED: "MISSION:ASSIGNED",
  MISSION_UPDATED: "MISSION:UPDATED",

  KPI_UPDATE: "KPI:UPDATE",
  MATERIAL_UPDATE: "MATERIAL:UPDATE",
};
